#---- Directory structure config ----

#---- Resources ----
#-------- References --------


#-------- Variant filtration ---------

#-------- Annotation --------

#---- Input ----
input_rna_dir: "input/RNA/"
"resource_dir": "resources/"
"panel_dir": "resources/panels/"
"reference_dir": "resources/reference/"
#----

#----
#---- Output directory and subdirectories ----
"out_dir": "results/"
#--------- Subdirectories --------
log_dir: "logs"
error_dir: "errors"
benchmark_dir: "benchmarks"
cluster_log_dir: "cluster_logs"

"qc_dir": "qc/"
#--------

#---- Conda ----
"conda_config": "workflow/envs/conda.yaml"
"arriba_config": "workflow/envs/arriba.yaml"
#----

#---- Tool threads ----
"threads":
  "merge_files": 1
  "fastqc": 1
  "cutadapt": 5
  "STAR": 5
  "arriba": 1
  "add_sample_id": 1
  "combine_arriba_fusion_files": 1
  "samtools_index": 2
  "sort_bam": 5
  "visualization" : 2
  "filter_arriba_output": 1
  "classify_genes": 1
  "trim_UMIs": 8
  "fastq_to_bam" : 3
  "extract_umis_from_bam": 2
  "sort": 2
  "fixmate": 1
  "umi_tools_extract_umi": 1
  "umi_tools_dedup": 1
#---- Tool memory ---- #TODO: adjust memory requirements
"memory_mb":
  "merge_files": 1000
  "fastqc": 8000
  "cutadapt": 10000
  "STAR": 40000
  "arriba": 15000
  "add_sample_id": 500
  "combine_arriba_fusion_files": 500
  "samtools_index": 3000
  "sort_bam_per_thread": 3000
  "visualization": 10000
  "filter_arriba_output": 500
  "classify_genes": 500
  "trim_UMIs": 3000
  "fastq_to_bam": 2000
  "extract_umis_from_bam": 5000
  "picard": 1
  "umi_tools_extract_umi": 3000
  "umi_tools_dedup": 14000
per_thread_sort_mem: 10 # memory in gigabytes

#---- Tool time ----
time:
  "merge_files": "00:15:00"
  "fastqc": "02:00:00"
  "cutadapt": "02:00:00"
  "STAR": "05:00:00"
  "arriba": "05:00:00"
  "add_sample_id": "00:10:00"
  "combine_arriba_fusion_files": "00:10:00"
  "samtools_index": "02:00:00"
  "sort_bam": "02:00:00"
  "visualization": "02:00:00"
  "filter_arriba_output": "00:10:00"
  "classify_genes": "00:10:00"
  "trim_UMIs": "02:00:00"
  "fastq_to_bam": "02:00:00"
  "extract_umis_from_bam": "02:00:00"
  "umi_tools_extract_umi": "02:00:00"
  "umi_tools_dedup": "05:00:00"
#---- Tool variables ----

"cutadapt":
    "minlength": 50
    "adapter_seq": "AGATCGGAAGAGC"
"fastqc":
    "kmer_length": 7
"filter_arriba_output":
    "min_coverage": 1
    "min_non_zero_sup_cov": 2
    "coverage_ratio_threshold": 0.001
    "min_supporting_ratios_above_threshold": 2
#---- Tool selection ----
"aligner_list":
  - "STAR"
"fusion_caller_list":
  - "arriba"
"umi_tools_dedup":
    "method": "unique"
    "spliced_is_unique": True
    "use_read_length": True
#----

"panel_parameters":
    "KAPA_HyperPETE_LC_Fusion_Panel":
        "UMI": True
        "UMI_type": "duplex"
        "use_UMI": True
        "forward_read_scheme": "3M3S+T" # necessary for handling UMIs via fgbio
        "reverse_read_scheme": "3M3S+T" # necessary for handling UMIs via fgbio
        "forward_barcode_length": 3 # necessary for handling UMIs via umi_tools. TODO: write parser, which will convert  fgbio UMIs to umi_tools regexp
        "forward_linker_length": 3
        "reverse_barcode_length": 3
        "reverse_linker_length": 3
        "forward_read_trim": 6 # number of bases to trim from 5' of forward read if "use_UMI" is set to False. Ignored if "UMI" is set to False
        "reverse_read_trim": 6 # number of bases to trim from 5' of reverse read if "use_UMI" is set to False. Ignored if "UMI" is set to False

"umi_handling_pipeline_stage_list":
    "umi_tools":
          - "sorted" # comment this line to skip analyses of data prior removal of duplicates.
          - "rmdup"

#---- Pipeline modes ----

#"starting_point": "fastq"
"pipeline_mode": "visualization" # Allowed: "qc", "filtering", "alignment", "fusion_call", "visualization"
"panel": "KAPA_HyperPETE_LC_Fusion_Panel"
"umi_handling_pipeline": "umi_tools" # Allowed: 'umi_tools'
"sample_list": []
#---- Data types ----
"data_type_description":
    "fastq":
        "input":
            "suffix_list":
                "forward":
                    - "_R1_001"
                "reverse":
                    - "_R2_001"
            "extension_list":
                - ".fastq.gz"
        "output":
            "suffix_list":
                "forward": "_1"
                "reverse": "_2"
            "extension": ".fastq.gz"
    "fasta":
        "input":
            "extension_list":
                - ".fa"
                - ".fasta"
        "output":
            "extension": ".fasta"
    "gtf":
        "input":
            "extension_list":
                - ".gtf"
        "output":
            "extension": ".gtf"
    "bam":
        "input":
            "extension_list":
                - ".bam"
        "output":
            "extension": ".bam"
    "sam":
        "input":
            "extension_list":
                - ".sam"
        "output":
            "extension": ".sam"