#---- Directory structure config ----

#---- Resources ----
#-------- References --------


#-------- Variant filtration ---------

#-------- Annotation --------

#---- Input ----
input_rna_dir: "input/RNA"
"reference_dir": "input/reference"
#----

#----
#---- Output directory and subdirectories ----
"out_dir": "results/"
#--------- Subdirectories --------
log_dir: "logs"
error_dir: "errors"
benchmark_dir: "benchmarks"
cluster_log_dir: "cluster_logs"

"qc_dir": "qc/"
#--------

#---- Conda ----
"conda_config": "workflow/envs/conda.yaml"
#----

#---- Tool threads ----
"threads":
  "merge_files": 1
  "fastqc": 1
  "cutadapt": 5
  "STAR": 5
  "arriba": 4

#---- Tool memory ---- #TODO: adjust memory requirements
"memory_mb":
  "merge_files": 1000
  "fastqc": 8000
  "cutadapt": 10000
  "STAR": 15000
  "arriba": 15000

per_thread_sort_mem: 10 # memory in gigabytes

#---- Tool time ----
time:
  "merge_files": "00:15:00"
  "fastqc": "02:00:00"
  "cutadapt": "02:00:00"
  "STAR": "05:00:00"
  "arriba": "05:00:00"

#---- Tool variables ----


cutadapt:
  minlength: 50
  adapter_seq: "AGATCGGAAGAGC"
fastqc:
  kmer_length: 7
mosdepth:
  min_mapping_quality: 20

#---- Report ----
report_type_list:
  - "full"

#---- Pipeline modes ----

#"starting_point": "fastq"
"pipeline_mode": "alignment"

"data_type_description":
    "fastq":
        "input":
            "suffix_list":
                "forward":
                    - "_R1_001"
                "reverse":
                    - "_R2_001"
            "extension_list":
                - ".fastq.gz"
        "output":
            "suffix_list":
                "forward": "_1"
                "reverse": "_2"
            "extension": ".fastq.gz"
    "fasta":
        "input":
            "extension_list":
                - ".fa"
                - ".fasta"
        "output":
            "extension": ".fasta"
    "gtf":
        "input":
            "extension_list":
                - ".gtf"
        "output":
            "extension": ".gtf"