#---- Directory structure config ----

#---- Resources ----
#-------- References --------


#-------- Variant filtration ---------

#-------- Annotation --------

#---- Input ----
input_rna_dir: "input/RNA"

#----

#----
#---- Output directory and subdirectories ----
"out_dir": "results/"
#--------- Subdirectories --------
#log_dir: "logs"
#error_dir: "errors"
#benchmark_dir: "benchmarks"
#cluster_log_dir: "cluster_logs"

"qc_dir": "qc/"
#--------

#---- Conda ----
"conda_config": "workflow/envs/conda.yaml"
#----

#---- Tool threads ----
"threads":
  "merge_files": 1
  "fastqc": 1
  "cutadapt": 5


  merge_reference: 1
  ref_faidx: 1
  ref_dict: 1
  bwa_index: 1
  bowtie2_index: 1

  bwa: 25
  bowtie2: 8
  sort: 2
  fixmate: 1
  index: 1
  mosdepth: 3
  basecall: 30
  add_umi_tag: 2
  group_reads_by_umi: 2
  create_consensus_reads: 2
  filter_consensus_reads: 2
  create_consensus_fastq: 1
  merge_target_regions: 1
  add_flanks_to_dna_regions: 1
  merge_overlapping_regions: 1
  extract_flanked_dna_regions: 1
  create_genome_size_file: 1
  pisces: 3
  index_gnomad: 1
  index_cosmic: 1
  preprocess_gnomad: 1
  preprocess_cosmic: 1
  mutect2_call: 3
  train_orientation_model: 2
  get_pileup_summaries: 2
  calculate_contamination: 2
  filter_mutect2_vcf: 2
  create_panel_of_normals: 2
  create_sample_map: 1
  create_vcf_db: 2
  bed2gff: 1
  featureCounts: 5
  snpEff: 2
  sift_cosmic: 2
  extract_annotation: 1
  remove_filtered_variant: 1
  normalize_variants: 2
  rna_total_gff: 1
  vep: 1
  merge_annotation: 1
  cp_dna_ref: 1
  cp_rna_ref: 1
  get_basecall_stats: 1
  gather_per_library_read_stats: 1
  merge_sample_read_stats: 1
  infer_replicates: 1
  rmdup_raw_reads: 1
  merge_target_regions_raw_reads: 1
  merge_all_annotation: 1
  gather_final_stats: 1
  merge_rna_fusion_regions: 1
  extract_synthetic_reads: 3
  get_fusion_pvalues: 1
  get_biological_counts: 1
  merge_rna_counts_by_replicates: 1
  fastq_to_sam: 3
  extract_umis_from_bam: 2
  picard: 1
  create_duplex_consensus_reads: 2
  merge_ontarget_regions: 1
  gather_duplication_rate_stats: 1
#---- Tool memory ---- #TODO: adjust memory requirements
"memory_mb":
  "merge_files": 1000
  "fastqc": 8000
  "cutadapt": 10000

  merge_reference: 1000
  ref_faidx: 1000
  ref_dict: 1000
  bwa_index: 10000

  trimmomatic: 10000

  index: 10000
  bwa: 10000
  bowtie2: 10000
  fixmate: 10000
  mosdepth: 4000 #The amount of memory is approximately equal to 32-bits * longest chrom length, so for the 249MB chromosome 1, it will require 1GB of memory.
  basecall: 20000
  add_umi_tag: 10000
  group_reads_by_umi: 10000
  create_consensus_reads: 5000
  filter_consensus_reads: 5000
  create_consensus_fastq: 20000
  vardict: 10000
  merge_target_regions: 1000
  create_genome_size_file: 10000
  pisces: 5000
  preprocess_gnomad: 5000
  preprocess_cosmic: 5000
  index_gnomad: 3000,
  index_cosmic: 3000,,
  mutect2_call: 15000 # during tests consumed up to 5% on 256 GB machine
  train_orientation_model: 10000
  get_pileup_summaries: 10000
  calculate_contamination: 10000
  filter_mutect2_vcf: 10000
  add_flanks_to_dna_regions: 1000
  merge_overlapping_regions: 1000
  extract_flanked_dna_regions: 5000
  bowtie2_index: 20000
  create_panel_of_normals: 20000
  create_sample_map: 500
  create_vcf_db: 5000
  bed2gff: 500
  featureCounts: 3000
  snpEff: 10000
  sift_cosmic: 10000
  extract_annotation: 500
  remove_filtered_variant: 300
  normalize_variants: 500
  rna_total_gff: 300
  vep: 3000
  merge_annotation: 1000
  cp_dna_ref: 1000
  cp_rna_ref: 1000
  get_basecall_stats: 100
  gather_per_library_read_stats: 100
  merge_sample_read_stats: 100
  infer_replicates: 100
  rmdup_raw_reads: 5000
  merge_target_regions_raw_reads: 100
  merge_all_annotation: 200
  gather_final_stats: 200
  merge_rna_fusion_regions: 200
  extract_synthetic_reads: 2000
  get_fusion_pvalues: 200
  get_biological_counts: 200
  merge_rna_counts_by_replicates: 1000
  fastq_to_sam: 5000
  extract_umis_from_bam: 5000
  picard: 10000
  create_duplex_consensus_reads: 5000
  merge_ontarget_regions: 100
  gather_duplication_rate_stats: 100
per_thread_sort_mem: 10 # memory in gigabytes

#---- Tool time ----
time:
  "merge_files": "00:15:00"
  "fastqc": "02:00:00"
  "cutadapt": "02:00:00"

  merge_reference: "01:00:00"
  ref_faidx: "00:30:00"
  ref_dict: "00:30:00"
  bwa_index: "10:00:00"

  trimmomatic: "10:00:00"

  index: "10:00:00"
  bwa_map: "05:00:00"
  bowtie2_rna_map: "05:00:00"
  mosdepth: "02:00:00"
  basecall: "10:00:00"
  add_umi_tag: "02:00:00"
  group_reads_by_umi: "02:00:00"
  create_consensus_reads: "02:00:00"
  filter_consensus_reads: "02:00:00"
  create_consensus_fastq: "02:00:00"
  vardict: "10:00:00"
  merge_target_regions: "00:30:00"
  create_genome_size_file: "02:00:00"
  pisces: "02:00:00"
  preprocess_gnomad: "02:00:00"
  preprocess_cosmic: "02:00:00"
  index_gnomad: "02:30:00"
  index_cosmic: "02:30:00"
  mutect2_call: "02:00:00"
  train_orientation_model: "02:00:00"
  get_pileup_summaries: "02:00:00"
  calculate_contamination: "02:00:00"
  filter_mutect2_vcf: "02:00:00"
  add_flanks_to_dna_regions: "00:10:00"
  merge_overlapping_regions: "00:10:00"
  extract_flanked_dna_regions: "01:00:00"
  bowtie2_index: "12:00:00"
  create_panel_of_normals: "12:00:00"
  create_sample_map: "00:05:00"
  create_vcf_db: "02:00:00"
  bed2gff: "00:10:00"
  featureCounts: "00:30:00"
  snpEff: "02:00:00"
  sift_cosmic: "02:00:00"
  extract_annotation: "00:10:00"
  remove_filtered_variant: "00:10:00"
  normalize_variants: "00:10:00"
  rna_total_gff: "00:10:00"
  vep: "00:30:00"
  merge_annotation: "00:05:00"
  cp_dna_ref: "00:10:00"
  cp_rna_ref: "00:10:00"
  get_basecall_stats: "00:10:00"
  gather_per_library_read_stats: "00:10:00"
  merge_sample_read_stats: "00:10:00"
  infer_replicates: "00:10:00"
  rmdup_raw_reads: "04:00:00"
  merge_target_regions_raw_reads: "00:10:00"
  merge_all_annotation: "00:10:00"
  gather_final_stats: "00:10:00"
  merge_rna_fusion_regions: "00:10:00"
  extract_synthetic_reads: "04:00:00"
  get_fusion_pvalues: "00:30:00"
  get_biological_counts: "00:10:00"
  merge_rna_counts_by_replicates: "00:30:00"
  fastq_to_sam: "04:00:00"
  extract_umis_from_bam: "02:00:00"
  create_duplex_consensus_reads: "02:00:00"
  merge_ontarget_regions: "00:10:00"
  gather_duplication_rate_stats: "00:10:00"


#---- Tool variables ----


cutadapt:
  minlength: 50
  adapter_seq: "AGATCGGAAGAGC"
fastqc:
  kmer_length: 7
mosdepth:
  min_mapping_quality: 20

#---- Report ----
report_type_list:
  - "full"

#---- Pipeline modes ----

"starting_point": "fastq"
"pipeline_mode": "filtering"

"data_type_description":
    "fastq":
        "input":
            "suffix_list":
                "forward":
                    - "_R1_001"
                "reverse":
                    - "_R2_001"
            "extension_list":
                - ".fastq.gz"
        "output":
            "suffix_list":
                "forward": "_1"
                "reverse": "_2"
            "extension": ".fastq.gz"