#---- Directory structure config ----

#---- Resources ----
#-------- References --------


#-------- Variant filtration ---------

#-------- Annotation --------

#---- Input ----
input_rna_dir: "input/RNA/"
"resource_dir": "resources/"
"panel_dir": "resources/panel/"
"reference_dir": "resources/reference/"
#----

#----
#---- Output directory and subdirectories ----
"out_dir": "results/"
#--------- Subdirectories --------
log_dir: "logs"
error_dir: "errors"
benchmark_dir: "benchmarks"
cluster_log_dir: "cluster_logs"

"qc_dir": "qc/"
#--------

#---- Conda ----
"conda_config": "workflow/envs/conda.yaml"
"arriba_config": "workflow/envs/arriba.yaml"
#----

#---- Tool threads ----
"threads":
  "merge_files": 1
  "fastqc": 1
  "cutadapt": 5
  "STAR": 5
  "arriba": 4
  "add_sample_id": 1
  "combine_arriba_fusion_files": 1
  "samtools_index": 2
  "sort_bam": 5
  "visualization" : 2
  "filter_arriba_output": 1
  "classify_genes": 1
#---- Tool memory ---- #TODO: adjust memory requirements
"memory_mb":
  "merge_files": 1000
  "fastqc": 8000
  "cutadapt": 10000
  "STAR": 40000
  "arriba": 15000
  "add_sample_id": 500
  "combine_arriba_fusion_files": 500
  "samtools_index": 3000
  "sort_bam_per_thread": 3000
  "visualization": 10000
  "filter_arriba_output": 500
  "classify_genes": 500
per_thread_sort_mem: 10 # memory in gigabytes

#---- Tool time ----
time:
  "merge_files": "00:15:00"
  "fastqc": "02:00:00"
  "cutadapt": "02:00:00"
  "STAR": "05:00:00"
  "arriba": "05:00:00"
  "add_sample_id": "00:10:00"
  "combine_arriba_fusion_files": "00:10:00"
  "samtools_index": "02:00:00"
  "sort_bam": "02:00:00"
  "visualization": "02:00:00"
  "filter_arriba_output": "00:10:00"
  "classify_genes": "00:10:00"
#---- Tool variables ----

"cutadapt":
    "minlength": 50
    "adapter_seq": "AGATCGGAAGAGC"
"fastqc":
    "kmer_length": 7
"filter_arriba_output":
    "min_coverage": 1
    "min_non_zero_sup_cov": 2
    "coverage_ratio_threshold": 0.001
    "min_supporting_ratios_above_threshold": 2
#---- Tool selection ----
"aligner_list":
  - "STAR"
"fusion_caller_list":
  - "arriba"

"panel_list":
    - "KAPA_HyperPETE_LC_Fusion_Panel"

#---- Pipeline modes ----

#"starting_point": "fastq"
"pipeline_mode": "visualization" # Allowed: "qc", "filtering", "alignment", "fusion_call", "visualization"
"panel": "KAPA_HyperPETE_LC_Fusion_Panel"

#---- Data types ----
"data_type_description":
    "fastq":
        "input":
            "suffix_list":
                "forward":
                    - "_R1_001"
                "reverse":
                    - "_R2_001"
            "extension_list":
                - ".fastq.gz"
        "output":
            "suffix_list":
                "forward": "_1"
                "reverse": "_2"
            "extension": ".fastq.gz"
    "fasta":
        "input":
            "extension_list":
                - ".fa"
                - ".fasta"
        "output":
            "extension": ".fasta"
    "gtf":
        "input":
            "extension_list":
                - ".gtf"
        "output":
            "extension": ".gtf"