#---- Bioconda config ----
name: interarray
channels:
  - bioconda
  - conda-forge
  - anaconda
dependencies:
  - python>=3.8
  #- bcl2fastq=2.19
  - fastqc>=0.11
  - cutadapt=3.4
  - fastx_toolkit
  #- fgbio
  - umi_tools
  #- bwa=0.7.17
  #- bowtie2=2.4
  #- samtools>=1.10
  #- mosdepth>=0.3.1
  #- gatk4=4.2.0.0
  #- picard>=2.5
  #- numpy>=1.10
  #- pandas>=1.2
  #- matplotlib
  #- fgbio=1.3.0
  #- bedtools>=2.26
  #- tabix
  #- subread=2
  #- snpeff=5.0
  #- snpsift=4.3
  #- statsmodels>=0.12
  #- pip
  #- bcftools
  #- xlsxwriter
#Installation via pip - fastqcparser
#Manual Installation - pisces=5.3

